'use client';

import { useState } from 'react';
import { SystemCategorization as SystemCategorizationType, InformationType, SecurityRequirement, AutoGeneratedRequirement, NISTInformationTypeStructure } from '../types/srtm';
import { Plus, Edit2, Trash2, Save, X, Shield, AlertCircle, CheckCircle, Zap } from 'lucide-react';

interface CategorizationProps {
  systemCategorizations: SystemCategorizationType[];
  onUpdate: (categorizations: SystemCategorizationType[]) => void;
  onGenerateRequirements: (requirements: SecurityRequirement[]) => void;
}

// NIST SP 800-60 Defense & National Security Information Types (Hierarchical Structure)
const NIST_INFORMATION_TYPES = [
  // D.1 - Combat Operations
  { category: "D.1", name: "Combat Operations", description: "Information supporting direct military combat operations and tactical activities", subtypes: [
    { category: "D.1.1", name: "Tactical Operations", description: "Real-time tactical battlefield operations and command decisions" },
    { category: "D.1.2", name: "Fire Control Systems", description: "Weapons systems targeting and fire control information" },
    { category: "D.1.3", name: "Battle Damage Assessment", description: "Post-engagement damage evaluation and effectiveness analysis" }
  ]},
  
  // D.2 - Strategic Planning
  { category: "D.2", name: "Strategic Planning", description: "Long-term defense strategy and policy development information", subtypes: [
    { category: "D.2.1", name: "Defense Strategy", description: "National defense strategy formulation and planning" },
    { category: "D.2.2", name: "Resource Allocation", description: "Strategic resource planning and budget allocation" },
    { category: "D.2.3", name: "Capability Development", description: "Future capability requirements and development planning" }
  ]},
  
  // D.3 - Intelligence Operations
  { category: "D.3", name: "Intelligence Operations", description: "Intelligence collection, analysis, and dissemination activities", subtypes: [
    { category: "D.3.1", name: "Collection Operations", description: "Intelligence gathering and surveillance operations" },
    { category: "D.3.2", name: "Analysis and Production", description: "Intelligence analysis and finished intelligence products" },
    { category: "D.3.3", name: "Counterintelligence", description: "Protection against foreign intelligence operations" }
  ]},
  
  // D.4 - Logistics and Supply
  { category: "D.4", name: "Logistics and Supply", description: "Military logistics, supply chain, and sustainment operations", subtypes: [
    { category: "D.4.1", name: "Supply Chain Management", description: "End-to-end supply chain coordination and management" },
    { category: "D.4.2", name: "Transportation", description: "Military transportation and movement operations" },
    { category: "D.4.3", name: "Maintenance Operations", description: "Equipment and systems maintenance and repair" }
  ]},
  
  // D.5 - Personnel and Readiness
  { category: "D.5", name: "Personnel and Readiness", description: "Military personnel management and readiness assessment", subtypes: [
    { category: "D.5.1", name: "Personnel Management", description: "Military personnel records and career management" },
    { category: "D.5.2", name: "Training and Education", description: "Military training programs and professional education" },
    { category: "D.5.3", name: "Readiness Assessment", description: "Unit readiness evaluation and reporting" }
  ]},
  
  // Additional categories abbreviated for brevity - would include D.6 through D.26
  { category: "D.6", name: "Communications and Networks", description: "Military communications systems and network operations" },
  { category: "D.7", name: "Cybersecurity Operations", description: "Defensive and offensive cyber operations" },
  { category: "D.8", name: "Research and Development", description: "Defense research, development, test, and evaluation" },
  { category: "D.9", name: "Acquisition and Procurement", description: "Defense acquisition and procurement processes" },
  { category: "D.10", name: "Installation Management", description: "Military installation operations and management" },
  
  // Management and Support Information Types (Cross-cutting)
  { category: "MS.1", name: "Financial Management", description: "Defense financial management and accounting", subtypes: [
    { category: "MS.1.1", name: "Budget Planning", description: "Defense budget formulation and planning" },
    { category: "MS.1.2", name: "Financial Reporting", description: "Financial statements and compliance reporting" },
    { category: "MS.1.3", name: "Cost Analysis", description: "Program cost analysis and estimation" }
  ]},
  
  { category: "MS.2", name: "Information Management", description: "Information systems and data management", subtypes: [
    { category: "MS.2.1", name: "Data Management", description: "Enterprise data governance and management" },
    { category: "MS.2.2", name: "Records Management", description: "Official records lifecycle management" },
    { category: "MS.2.3", name: "Knowledge Management", description: "Organizational knowledge capture and sharing" }
  ]}
];

// Security Control Baselines based on NIST SP 800-53
const SECURITY_CONTROL_BASELINES = {
  Low: [
    "AC-1", "AC-2", "AC-3", "AC-7", "AC-8", "AC-14", "AC-17", "AC-18", "AC-19", "AC-20", "AC-22",
    "AT-1", "AT-2", "AT-3", "AT-4",
    "AU-1", "AU-2", "AU-3", "AU-4", "AU-5", "AU-6", "AU-8", "AU-9", "AU-11", "AU-12",
    "CA-1", "CA-2", "CA-3", "CA-5", "CA-6", "CA-7", "CA-9",
    "CM-1", "CM-2", "CM-4", "CM-5", "CM-6", "CM-7", "CM-8", "CM-10", "CM-11",
    "CP-1", "CP-2", "CP-3", "CP-4", "CP-9", "CP-10",
    "IA-1", "IA-2", "IA-3", "IA-4", "IA-5", "IA-6", "IA-7", "IA-8",
    "IR-1", "IR-2", "IR-3", "IR-4", "IR-5", "IR-6", "IR-7", "IR-8",
    "MA-1", "MA-2", "MA-4", "MA-5",
    "MP-1", "MP-2", "MP-6", "MP-7",
    "PE-1", "PE-2", "PE-3", "PE-6", "PE-8", "PE-12", "PE-13", "PE-14", "PE-15", "PE-16",
    "PL-1", "PL-2", "PL-4",
    "PS-1", "PS-2", "PS-3", "PS-4", "PS-5", "PS-6", "PS-7", "PS-8",
    "RA-1", "RA-3", "RA-5",
    "SA-1", "SA-2", "SA-3", "SA-4", "SA-5", "SA-9", "SA-11",
    "SC-1", "SC-2", "SC-4", "SC-5", "SC-7", "SC-12", "SC-13", "SC-15", "SC-20", "SC-21", "SC-22",
    "SI-1", "SI-2", "SI-3", "SI-4", "SI-5", "SI-12"
  ],
  Moderate: [
    // Include all Low controls plus additional Moderate controls
    "AC-1", "AC-2", "AC-3", "AC-4", "AC-5", "AC-6", "AC-7", "AC-8", "AC-11", "AC-12", "AC-14", "AC-17", "AC-18", "AC-19", "AC-20", "AC-22",
    "AT-1", "AT-2", "AT-3", "AT-4",
    "AU-1", "AU-2", "AU-3", "AU-4", "AU-5", "AU-6", "AU-7", "AU-8", "AU-9", "AU-10", "AU-11", "AU-12",
    "CA-1", "CA-2", "CA-3", "CA-5", "CA-6", "CA-7", "CA-8", "CA-9",
    "CM-1", "CM-2", "CM-3", "CM-4", "CM-5", "CM-6", "CM-7", "CM-8", "CM-9", "CM-10", "CM-11",
    "CP-1", "CP-2", "CP-3", "CP-4", "CP-6", "CP-7", "CP-8", "CP-9", "CP-10",
    "IA-1", "IA-2", "IA-3", "IA-4", "IA-5", "IA-6", "IA-7", "IA-8",
    "IR-1", "IR-2", "IR-3", "IR-4", "IR-5", "IR-6", "IR-7", "IR-8",
    "MA-1", "MA-2", "MA-3", "MA-4", "MA-5", "MA-6",
    "MP-1", "MP-2", "MP-3", "MP-4", "MP-5", "MP-6", "MP-7",
    "PE-1", "PE-2", "PE-3", "PE-4", "PE-5", "PE-6", "PE-8", "PE-9", "PE-10", "PE-11", "PE-12", "PE-13", "PE-14", "PE-15", "PE-16", "PE-17",
    "PL-1", "PL-2", "PL-4", "PL-8",
    "PS-1", "PS-2", "PS-3", "PS-4", "PS-5", "PS-6", "PS-7", "PS-8",
    "RA-1", "RA-2", "RA-3", "RA-5",
    "SA-1", "SA-2", "SA-3", "SA-4", "SA-5", "SA-8", "SA-9", "SA-10", "SA-11",
    "SC-1", "SC-2", "SC-3", "SC-4", "SC-5", "SC-7", "SC-8", "SC-10", "SC-11", "SC-12", "SC-13", "SC-15", "SC-17", "SC-18", "SC-19", "SC-20", "SC-21", "SC-22", "SC-23",
    "SI-1", "SI-2", "SI-3", "SI-4", "SI-5", "SI-7", "SI-8", "SI-10", "SI-11", "SI-12"
  ],
  High: [
    // Include all Moderate controls plus additional High controls - this would be the complete set
    "AC-1", "AC-2", "AC-3", "AC-4", "AC-5", "AC-6", "AC-7", "AC-8", "AC-9", "AC-10", "AC-11", "AC-12", "AC-13", "AC-14", "AC-15", "AC-16", "AC-17", "AC-18", "AC-19", "AC-20", "AC-21", "AC-22", "AC-23", "AC-24", "AC-25",
    // ... (would include all families with enhancements)
  ]
};

// Control descriptions and mappings
const CONTROL_DETAILS: { [key: string]: AutoGeneratedRequirement } = {
  "AC-1": {
    controlId: "AC-1",
    controlFamily: "AC",
    title: "Access Control Policy and Procedures",
    description: "The organization develops, documents, and disseminates an access control policy and implements access control procedures.",
    priority: "High",
    nistFunction: "Protect",
    rmfStep: "Select"
  },
  "AC-2": {
    controlId: "AC-2",
    controlFamily: "AC",
    title: "Account Management",
    description: "The organization manages information system accounts including establishing, activating, modifying, disabling, and removing accounts.",
    priority: "High",
    nistFunction: "Protect",
    rmfStep: "Implement"
  },
  "AC-3": {
    controlId: "AC-3",
    controlFamily: "AC",
    title: "Access Enforcement",
    description: "The information system enforces approved authorizations for logical access to information and system resources.",
    priority: "High",
    nistFunction: "Protect",
    rmfStep: "Implement"
  },
  // Add more control details as needed...
};

export default function SystemCategorization({ systemCategorizations, onUpdate, onGenerateRequirements }: CategorizationProps) {
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showRequirements, setShowRequirements] = useState<string | null>(null);
  const [formData, setFormData] = useState<Partial<SystemCategorizationType>>({
    systemName: '',
    systemDescription: '',
    informationTypes: [],
    overallCategorization: {
      confidentiality: 'Low',
      integrity: 'Low',
      availability: 'Low'
    },
    rationale: ''
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (editingId) {
      const updated = systemCategorizations.map(cat => 
        cat.id === editingId 
          ? { ...cat, ...formData, updatedAt: new Date() }
          : cat
      );
      onUpdate(updated);
    } else {
      const newCategorization: SystemCategorizationType = {
        id: Date.now().toString(),
        systemName: formData.systemName!,
        systemDescription: formData.systemDescription!,
        informationTypes: formData.informationTypes!,
        overallCategorization: formData.overallCategorization!,
        rationale: formData.rationale!,
        createdAt: new Date(),
        updatedAt: new Date()
      };
      onUpdate([...systemCategorizations, newCategorization]);
    }

    resetForm();
  };

  const handleEdit = (categorization: SystemCategorizationType) => {
    setFormData(categorization);
    setEditingId(categorization.id);
    setIsFormOpen(true);
  };

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this system categorization?')) {
      onUpdate(systemCategorizations.filter(cat => cat.id !== id));
    }
  };

  const resetForm = () => {
    setFormData({
      systemName: '',
      systemDescription: '',
      informationTypes: [],
      overallCategorization: {
        confidentiality: 'Low',
        integrity: 'Low',
        availability: 'Low'
      },
      rationale: ''
    });
    setEditingId(null);
    setIsFormOpen(false);
  };

  const addInformationType = () => {
    const newType: InformationType = {
      id: Date.now().toString(),
      name: '',
      description: '',
      category: '',
      confidentialityImpact: 'Low',
      integrityImpact: 'Low',
      availabilityImpact: 'Low'
    };
    setFormData(prev => ({
      ...prev,
      informationTypes: [...(prev.informationTypes || []), newType]
    }));
  };

  const updateInformationType = (index: number, updates: Partial<InformationType>) => {
    setFormData(prev => ({
      ...prev,
      informationTypes: prev.informationTypes?.map((type, i) => 
        i === index ? { ...type, ...updates } : type
      )
    }));
  };

  const removeInformationType = (index: number) => {
    setFormData(prev => ({
      ...prev,
      informationTypes: prev.informationTypes?.filter((_, i) => i !== index)
    }));
  };

  const calculateOverallImpact = () => {
    const types = formData.informationTypes || [];
    if (types.length === 0) return;

    const getHighestImpact = (impacts: string[]) => {
      if (impacts.includes('High')) return 'High';
      if (impacts.includes('Moderate')) return 'Moderate';
      return 'Low';
    };

    const confidentiality = getHighestImpact(types.map(t => t.confidentialityImpact));
    const integrity = getHighestImpact(types.map(t => t.integrityImpact));
    const availability = getHighestImpact(types.map(t => t.availabilityImpact));

    setFormData(prev => ({
      ...prev,
      overallCategorization: {
        confidentiality: confidentiality as 'Low' | 'Moderate' | 'High',
        integrity: integrity as 'Low' | 'Moderate' | 'High',
        availability: availability as 'Low' | 'Moderate' | 'High'
      }
    }));
  };

  const generateSecurityRequirements = (categorization: SystemCategorizationType) => {
    const highestImpact = getHighestOverallImpact(categorization.overallCategorization);
    const controlIds = SECURITY_CONTROL_BASELINES[highestImpact] || SECURITY_CONTROL_BASELINES.Low;
    
    const requirements: SecurityRequirement[] = controlIds.map(controlId => {
      const controlDetail = CONTROL_DETAILS[controlId] || {
        controlId,
        controlFamily: controlId.split('-')[0],
        title: `${controlId} - Security Control`,
        description: `Implementation of NIST SP 800-53 control ${controlId}`,
        priority: 'Medium' as const,
        nistFunction: 'Protect' as const,
        rmfStep: 'Select' as const
      };

      return {
        id: `${categorization.id}-${controlId}-${Date.now()}`,
        title: controlDetail.title,
        description: controlDetail.description,
        source: `NIST SP 800-53 (${highestImpact} Baseline)`,
        category: getControlCategory(controlDetail.controlFamily),
        priority: controlDetail.priority,
        status: 'Draft' as const,
        nistFunction: controlDetail.nistFunction,
        rmfStep: controlDetail.rmfStep,
        controlFamily: controlDetail.controlFamily,
        controlIdentifier: controlDetail.controlId,
        createdAt: new Date(),
        updatedAt: new Date()
      };
    });

    onGenerateRequirements(requirements);
  };

  const getHighestOverallImpact = (categorization: { confidentiality: string; integrity: string; availability: string }) => {
    const impacts = [categorization.confidentiality, categorization.integrity, categorization.availability];
    if (impacts.includes('High')) return 'High';
    if (impacts.includes('Moderate')) return 'Moderate';
    return 'Low';
  };

  const getControlCategory = (family: string) => {
    const familyMap: { [key: string]: any } = {
      'AC': 'Access Control',
      'AT': 'Authentication',
      'AU': 'Audit',
      'CA': 'Authorization',
      'CM': 'System Integrity',
      'CP': 'Incident Response',
      'IA': 'Authentication',
      'IR': 'Incident Response',
      'MA': 'System Integrity',
      'MP': 'Data Protection',
      'PE': 'Access Control',
      'PL': 'System Integrity',
      'PS': 'Access Control',
      'RA': 'System Integrity',
      'SA': 'System Integrity',
      'SC': 'Network Security',
      'SI': 'System Integrity'
    };
    return familyMap[family] || 'Other';
  };

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case 'High': return 'text-red-600 bg-red-100';
      case 'Moderate': return 'text-yellow-600 bg-yellow-100';
      case 'Low': return 'text-green-600 bg-green-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getParentCategoryDisplay = (category: string) => {
    // Check if this is a subtype by looking for it in the subtypes arrays
    for (const mainType of NIST_INFORMATION_TYPES) {
      if (mainType.subtypes) {
        const subtype = mainType.subtypes.find(st => st.category === category);
        if (subtype) {
          return `${category} (under ${mainType.category} - ${mainType.name})`;
        }
      }
    }
    // If not found as a subtype, it's a main category
    return category;
  };

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">System Categorization</h2>
          <p className="text-gray-600">NIST SP 800-60 Information System Categorization</p>
        </div>
        <button
          onClick={() => setIsFormOpen(true)}
          className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          <Plus className="h-4 w-4 mr-2" />
          New Categorization
        </button>
      </div>

      {/* Form Modal */}
      {isFormOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-4xl mx-4 max-h-screen overflow-y-auto">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">
                {editingId ? 'Edit System Categorization' : 'New System Categorization'}
              </h3>
              <button onClick={resetForm} className="text-gray-500 hover:text-gray-700">
                <X className="h-5 w-5" />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    System Name *
                  </label>
                  <input
                    type="text"
                    value={formData.systemName || ''}
                    onChange={(e) => setFormData(prev => ({ ...prev, systemName: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    System Description *
                  </label>
                  <textarea
                    value={formData.systemDescription || ''}
                    onChange={(e) => setFormData(prev => ({ ...prev, systemDescription: e.target.value }))}
                    rows={2}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  />
                </div>
              </div>

              {/* Information Types */}
              <div>
                <div className="flex justify-between items-center mb-3">
                  <label className="block text-sm font-medium text-gray-700">
                    Information Types
                  </label>
                  <button
                    type="button"
                    onClick={addInformationType}
                    className="text-sm px-3 py-1 bg-blue-100 text-blue-700 rounded-md hover:bg-blue-200"
                  >
                    Add Information Type
                  </button>
                </div>

                <div className="space-y-4">
                  {formData.informationTypes?.map((infoType, index) => (
                    <div key={index} className="border rounded-lg p-4 bg-gray-50">
                      <div className="flex justify-between items-start mb-3">
                        <h4 className="font-medium text-gray-900">Information Type {index + 1}</h4>
                        <button
                          type="button"
                          onClick={() => removeInformationType(index)}
                          className="text-red-600 hover:text-red-800"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <div>
                          <label className="block text-xs font-medium text-gray-700 mb-1">
                            NIST Category
                          </label>
                          <select
                            value={infoType.category}
                            onChange={(e) => {
                              // First check main categories
                              let selectedType = NIST_INFORMATION_TYPES.find(t => t.category === e.target.value);
                              
                              // If not found in main categories, check subtypes
                              if (!selectedType) {
                                for (const mainType of NIST_INFORMATION_TYPES) {
                                  if (mainType.subtypes) {
                                    selectedType = mainType.subtypes.find(st => st.category === e.target.value);
                                    if (selectedType) break;
                                  }
                                }
                              }
                              
                              updateInformationType(index, {
                                category: e.target.value,
                                name: selectedType?.name || '',
                                description: selectedType?.description || ''
                              });
                            }}
                            className="w-full px-2 py-1 text-sm border border-gray-300 rounded-md"
                          >
                            <option value="">Select Category</option>
                            {NIST_INFORMATION_TYPES.map(type => [
                              <option key={type.category} value={type.category}>
                                {type.category} - {type.name}
                              </option>,
                              ...(type.subtypes || []).map(subtype => (
                                <option key={subtype.category} value={subtype.category}>
                                  &nbsp;&nbsp;{subtype.category} - {subtype.name} (under {type.category} - {type.name})
                                </option>
                              ))
                            ]).flat()}
                          </select>
                        </div>
                        <div>
                          <label className="block text-xs font-medium text-gray-700 mb-1">
                            Name
                          </label>
                          <input
                            type="text"
                            value={infoType.name}
                            onChange={(e) => updateInformationType(index, { name: e.target.value })}
                            className="w-full px-2 py-1 text-sm border border-gray-300 rounded-md"
                          />
                        </div>
                      </div>

                      <div className="mb-4">
                        <label className="block text-xs font-medium text-gray-700 mb-1">
                          Description
                        </label>
                        <textarea
                          value={infoType.description}
                          onChange={(e) => updateInformationType(index, { description: e.target.value })}
                          rows={2}
                          className="w-full px-2 py-1 text-sm border border-gray-300 rounded-md"
                        />
                      </div>

                      <div className="grid grid-cols-3 gap-4">
                        <div>
                          <label className="block text-xs font-medium text-gray-700 mb-1">
                            Confidentiality Impact
                          </label>
                          <select
                            value={infoType.confidentialityImpact}
                            onChange={(e) => {
                              updateInformationType(index, { confidentialityImpact: e.target.value as any });
                              setTimeout(calculateOverallImpact, 100);
                            }}
                            className="w-full px-2 py-1 text-sm border border-gray-300 rounded-md"
                          >
                            <option value="Low">Low</option>
                            <option value="Moderate">Moderate</option>
                            <option value="High">High</option>
                          </select>
                        </div>
                        <div>
                          <label className="block text-xs font-medium text-gray-700 mb-1">
                            Integrity Impact
                          </label>
                          <select
                            value={infoType.integrityImpact}
                            onChange={(e) => {
                              updateInformationType(index, { integrityImpact: e.target.value as any });
                              setTimeout(calculateOverallImpact, 100);
                            }}
                            className="w-full px-2 py-1 text-sm border border-gray-300 rounded-md"
                          >
                            <option value="Low">Low</option>
                            <option value="Moderate">Moderate</option>
                            <option value="High">High</option>
                          </select>
                        </div>
                        <div>
                          <label className="block text-xs font-medium text-gray-700 mb-1">
                            Availability Impact
                          </label>
                          <select
                            value={infoType.availabilityImpact}
                            onChange={(e) => {
                              updateInformationType(index, { availabilityImpact: e.target.value as any });
                              setTimeout(calculateOverallImpact, 100);
                            }}
                            className="w-full px-2 py-1 text-sm border border-gray-300 rounded-md"
                          >
                            <option value="Low">Low</option>
                            <option value="Moderate">Moderate</option>
                            <option value="High">High</option>
                          </select>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Overall Categorization */}
              <div className="border-t pt-4">
                <h4 className="font-medium text-gray-900 mb-3">Overall System Categorization</h4>
                <div className="grid grid-cols-3 gap-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Confidentiality
                    </label>
                    <select
                      value={formData.overallCategorization?.confidentiality || 'Low'}
                      onChange={(e) => setFormData(prev => ({
                        ...prev,
                        overallCategorization: {
                          ...prev.overallCategorization!,
                          confidentiality: e.target.value as any
                        }
                      }))}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="Low">Low</option>
                      <option value="Moderate">Moderate</option>
                      <option value="High">High</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Integrity
                    </label>
                    <select
                      value={formData.overallCategorization?.integrity || 'Low'}
                      onChange={(e) => setFormData(prev => ({
                        ...prev,
                        overallCategorization: {
                          ...prev.overallCategorization!,
                          integrity: e.target.value as any
                        }
                      }))}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="Low">Low</option>
                      <option value="Moderate">Moderate</option>
                      <option value="High">High</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Availability
                    </label>
                    <select
                      value={formData.overallCategorization?.availability || 'Low'}
                      onChange={(e) => setFormData(prev => ({
                        ...prev,
                        overallCategorization: {
                          ...prev.overallCategorization!,
                          availability: e.target.value as any
                        }
                      }))}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="Low">Low</option>
                      <option value="Moderate">Moderate</option>
                      <option value="High">High</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Rationale
                  </label>
                  <textarea
                    value={formData.rationale || ''}
                    onChange={(e) => setFormData(prev => ({ ...prev, rationale: e.target.value }))}
                    rows={3}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Explain the rationale for this categorization..."
                  />
                </div>
              </div>

              <div className="flex justify-end space-x-3 pt-4">
                <button
                  type="button"
                  onClick={resetForm}
                  className="px-4 py-2 text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                >
                  <Save className="h-4 w-4 mr-2" />
                  {editingId ? 'Update' : 'Create'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Categorizations List */}
      <div className="space-y-4">
        {systemCategorizations.length === 0 ? (
          <div className="bg-white rounded-lg border p-8 text-center">
            <Shield className="h-12 w-12 mx-auto mb-4 text-gray-300" />
            <p className="text-lg font-medium text-gray-900 mb-2">No System Categorizations</p>
            <p className="text-gray-500">Create a system categorization to begin security control selection.</p>
          </div>
        ) : (
          systemCategorizations.map((categorization) => (
            <div key={categorization.id} className="bg-white rounded-lg border p-6">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <h3 className="text-lg font-semibold text-gray-900">{categorization.systemName}</h3>
                  <p className="text-gray-600">{categorization.systemDescription}</p>
                </div>
                <div className="flex items-center space-x-2">
                  <button
                    onClick={() => generateSecurityRequirements(categorization)}
                    className="flex items-center px-3 py-1 bg-green-600 text-white text-sm rounded-lg hover:bg-green-700 transition-colors"
                  >
                    <Zap className="h-4 w-4 mr-1" />
                    Generate Requirements
                  </button>
                  <button
                    onClick={() => handleEdit(categorization)}
                    className="text-blue-600 hover:text-blue-900"
                  >
                    <Edit2 className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() => handleDelete(categorization.id)}
                    className="text-red-600 hover:text-red-900"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>

              {/* Overall Categorization Display */}
              <div className="mb-4">
                <h4 className="text-sm font-medium text-gray-900 mb-2">Overall System Impact</h4>
                <div className="grid grid-cols-3 gap-4">
                  <div className="text-center">
                    <div className="text-xs text-gray-500">Confidentiality</div>
                    <div className={`inline-block px-2 py-1 text-xs font-medium rounded-full ${getImpactColor(categorization.overallCategorization.confidentiality)}`}>
                      {categorization.overallCategorization.confidentiality}
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="text-xs text-gray-500">Integrity</div>
                    <div className={`inline-block px-2 py-1 text-xs font-medium rounded-full ${getImpactColor(categorization.overallCategorization.integrity)}`}>
                      {categorization.overallCategorization.integrity}
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="text-xs text-gray-500">Availability</div>
                    <div className={`inline-block px-2 py-1 text-xs font-medium rounded-full ${getImpactColor(categorization.overallCategorization.availability)}`}>
                      {categorization.overallCategorization.availability}
                    </div>
                  </div>
                </div>
              </div>

              {/* Information Types */}
              {categorization.informationTypes.length > 0 && (
                <div className="mb-4">
                  <h4 className="text-sm font-medium text-gray-900 mb-2">Information Types ({categorization.informationTypes.length})</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                    {categorization.informationTypes.map((infoType, index) => (
                      <div key={index} className="bg-gray-50 rounded-lg p-3">
                        <div className="text-sm font-medium text-gray-900">{infoType.name}</div>
                        <div className="text-xs text-gray-500">{getParentCategoryDisplay(infoType.category)}</div>
                        <div className="flex space-x-1 mt-2">
                          <span className={`px-1 py-0.5 text-xs rounded ${getImpactColor(infoType.confidentialityImpact)}`}>
                            C: {infoType.confidentialityImpact}
                          </span>
                          <span className={`px-1 py-0.5 text-xs rounded ${getImpactColor(infoType.integrityImpact)}`}>
                            I: {infoType.integrityImpact}
                          </span>
                          <span className={`px-1 py-0.5 text-xs rounded ${getImpactColor(infoType.availabilityImpact)}`}>
                            A: {infoType.availabilityImpact}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Baseline Information */}
              <div className="border-t pt-4">
                <div className="flex items-center justify-between text-sm text-gray-600">
                  <span>
                    Security Control Baseline: <strong className={`${getImpactColor(getHighestOverallImpact(categorization.overallCategorization))}`}>
                      {getHighestOverallImpact(categorization.overallCategorization)}
                    </strong>
                  </span>
                  <span>
                    Controls: {SECURITY_CONTROL_BASELINES[getHighestOverallImpact(categorization.overallCategorization)]?.length || 0}
                  </span>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}